export * from './auth.route';
export * from './metrics.route';
export * from './health.route';
export * from './version.route';
export * from './sse.route';
export * from './callback.route';
export * from './user.route';
export * from './twitch.route';
export * from './warcraft.route';
