import { Module } from '@nestjs/common';
import {
	KafkaModule as BaseModule,
	AzkabanAuthTopicArray,
	AzkabanCronjobTopicArray,
	AzkabanEmailTopicArray,
	AzkabanGroupTopicArray,
	AzkabanNotificationTopicArray,
	AzkabanSSETopicArray,
	AzkabanUserTopicArray,
	FoodFolioCategoryTopicArray,
	FoodFolioCompanyTopicArray,
	FoodFolioItemDetailTopicArray,
	FoodFolioItemTopicArray,
	FoodFolioItemVariantTopicArray,
	FoodFolioLocationTopicArray,
	FoodFolioShoppinglistTopicArray,
	FoodFolioSizeTopicArray,
	FoodFolioTypeTopicArray,
	FoodFolioWarehouseTopicArray,
	TwitchApiTopicArray,
	TwitchBotTopicArray,
	TwitchChannelTopicArray,
	TwitchMessageTopicArray,
	TwitchStreamTopicArray,
	TwitchViewerTopicArray,
	WarcraftApiTopicArray,
	WarcraftCharacterTopicArray,
	WarcraftRaiderTopicArray,
	CoworkingTasksTopicArray,
	WarcraftAuditTopicArray,
	AzkabanWebhookTopicArray,
} from '@azkaban/shared';

@Module({
	imports: [
		BaseModule.forRoot(
			true,
			{
				clientId: 'gateway',
				groupId: 'gateway-consumer',
				brokerHost: process.env.BROKER_HOST,
				brokerPort: Number(process.env.BROKER_PORT),
			},
			[
				...AzkabanAuthTopicArray,
				...AzkabanCronjobTopicArray,
				...AzkabanEmailTopicArray,
				...AzkabanGroupTopicArray,
				...AzkabanNotificationTopicArray,
				...AzkabanSSETopicArray,
				...AzkabanUserTopicArray,
				...AzkabanWebhookTopicArray,
				...FoodFolioCategoryTopicArray,
				...FoodFolioCompanyTopicArray,
				...FoodFolioItemTopicArray,
				...FoodFolioItemDetailTopicArray,
				...FoodFolioItemVariantTopicArray,
				...FoodFolioLocationTopicArray,
				...FoodFolioShoppinglistTopicArray,
				...FoodFolioSizeTopicArray,
				...FoodFolioTypeTopicArray,
				...FoodFolioWarehouseTopicArray,
				...TwitchApiTopicArray,
				...TwitchBotTopicArray,
				...TwitchChannelTopicArray,
				...TwitchMessageTopicArray,
				...TwitchStreamTopicArray,
				...TwitchViewerTopicArray,
				...WarcraftApiTopicArray,
				...WarcraftCharacterTopicArray,
				...WarcraftRaiderTopicArray,
				...WarcraftAuditTopicArray,
				...CoworkingTasksTopicArray,
			],
		),
	],
})
export class KafkaModule {}
