import { Module } from '@nestjs/common';
import {
	AzkabanAuthTopicArray,
	AzkabanCronjobTopicArray,
	AzkabanEmailTopicArray,
	AzkabanGroupTopicArray,
	AzkabanSSETopicArray,
	AzkabanUserTopicArray,
	AzkabanWebhookTopicArray,
	BlogCommentTopicArray,
	BlogNewsTopicArray,
	CoworkingTasksTopicArray,
	DiscordAscendApplyBotTopicArray,
	DiscordAscendJoinBotTopicArray,
	FoodFolioCategoryTopicArray,
	FoodFolioCompanyTopicArray,
	FoodFolioItemDetailTopicArray,
	FoodFolioItemTopicArray,
	FoodFolioItemVariantTopicArray,
	FoodFolioLocationTopicArray,
	FoodFolioShoppinglistTopicArray,
	FoodFolioSizeTopicArray,
	FoodFolioTypeTopicArray,
	FoodFolioWarehouseTopicArray,
	KafkaModule as BaseModule,
	TwitchApiTopicArray,
	TwitchBotTopicArray,
	TwitchChannelTopicArray,
	TwitchFollowerTopicArray,
	TwitchMessageTopicArray,
	TwitchStreamTopicArray,
	TwitchViewerTopicArray,
	WarcraftApiTopicArray,
	WarcraftAuditTopicArray,
	WarcraftCharacterTopicArray,
	WarcraftGuildTopicArray,
	WarcraftRaiderTopicArray,
} from '@azkaban/shared';
import { AppConfig } from '../../config';

@Module({
	imports: [
		BaseModule.forRoot(
			true,
			{
				clientId: AppConfig.name,
				groupId: AppConfig.name + '-consumer',
				brokerHost: AppConfig.broker.brokerHost,
				brokerPort: AppConfig.broker.brokerPort,
				brokerUsername: AppConfig.broker.brokerUsername,
				brokerPassword: AppConfig.broker.brokerPassword,
			},
			[
				// Azkaban Services
				...AzkabanAuthTopicArray,
				...AzkabanUserTopicArray,
				...AzkabanGroupTopicArray,
				...AzkabanCronjobTopicArray,
				...AzkabanEmailTopicArray,
				...AzkabanSSETopicArray,
				...AzkabanWebhookTopicArray,
				// Blog Services
				...BlogNewsTopicArray,
				...BlogCommentTopicArray,
				// Coworking Services
				...CoworkingTasksTopicArray,
				// Discord Services
				...DiscordAscendJoinBotTopicArray,
				...DiscordAscendApplyBotTopicArray,
				// Foodfolio Services
				...FoodFolioCategoryTopicArray,
				...FoodFolioCompanyTopicArray,
				...FoodFolioLocationTopicArray,
				...FoodFolioTypeTopicArray,
				...FoodFolioSizeTopicArray,
				...FoodFolioItemTopicArray,
				...FoodFolioItemDetailTopicArray,
				...FoodFolioItemVariantTopicArray,
				...FoodFolioWarehouseTopicArray,
				...FoodFolioShoppinglistTopicArray,
				// Twitch Services
				...TwitchBotTopicArray,
				...TwitchViewerTopicArray,
				...TwitchMessageTopicArray,
				...TwitchStreamTopicArray,
				...TwitchChannelTopicArray,
				...TwitchApiTopicArray,
				...TwitchFollowerTopicArray,
				...TwitchFollowerTopicArray,
				// Warcraft Services
				...WarcraftApiTopicArray,
				...WarcraftCharacterTopicArray,
				...WarcraftRaiderTopicArray,
				...WarcraftAuditTopicArray,
				...WarcraftGuildTopicArray,
			],
		),
	],
})
export class KafkaModule {}
