name: Release

on:
    push:
        branches: [release]

env:
    NX_BRANCH: ${GITHUB_REF##*/}

jobs:
    Release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Major version for each merge
              id: taggerDryRun
              uses: anothrNick/github-tag-action@1.71.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  WITH_V: true
                  DRY_RUN: true
                  DEFAULT_BUMP: major
                  PRE_RELEASE: false

            - name: echo new tag
              run: |
                  echo "${{ steps.taggerDryRun.outputs.new_tag }}"

            - name: API Alerts Notify
              uses: apialerts/notify-action@v1
              with:
                  api_key: ${{ secrets.API_ALERTS_KEY }}
                  message: '🚢 Feature - New Version Released (${{ steps.taggerDryRun.outputs.new_tag }})'
                  tags: 'Azkaban,Release'
                  link: 'https://github.com/ToxicToast/Azkaban_V4'
